name: CI (PR) - Tests/SAST/SCA/TF-Plan

on:
  pull_request:
    branches: ["main"]

jobs:
  #Checking if any file in infra has been changed
  changes:
    runs-on: ubuntu-latest
    outputs:
      infra: ${{ steps.filter.outputs.infra }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            infra:
              - 'infra/**'

  secrets_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2 #if any secrets found, default failed job

  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "17"

    - name: Run tests
      run: mvn test
      
  sast:
    needs: unit_tests
    uses: ./.github/workflows/sast-scan.yml
    secrets: inherit

  sca:
    needs: unit_tests
    uses: ./.github/workflows/sca-scan.yml
    secrets: inherit

  iac_scan:
    name: IaC scan (checkov)
    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{ needs.changes.outputs.infra == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Checkov scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra

  tf_plan:
    name: Terraform Plan (if infra changed)
    runs-on: ubuntu-latest
    needs: [changes, sast, sca]
    if: ${{ needs.changes.outputs.infra == 'true' }}
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"
      # For backend azurerm
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Terraform fmt/init/validate/plan
        run: |
          terraform fmt -check -recursive
          terraform init
          terraform validate
          terraform plan -var-file=dev.tfvars

  container_build_and_scan:
    name: Docker build + Trivy scan
    runs-on: ubuntu-latest
    needs: [secret_scan, sast, sca]
    steps:
      - uses: actions/checkout@v4
      - name: Build image (local)
        run: |
          docker build -t mywebapp:pr ./MyWebApp

      - name: Trivy scan image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: mywebapp:pr
          format: table
          exit-code: "1"
          severity: "CRITICAL, HIGH"
          ignore-unfixed: true

  sbom:
    name: generate sbom
    runs-on: ubuntu-latest
    needs: [container_build_and_scan]
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t mywebapp:pr ./MyWebApp

      - name: generate sbom
        uses: anchore/sbom-action@v0
        with:
          image: mywebapp:pr
          format: spdx-json
          output-file: sbom.spdx.json

      - name: upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json
